import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { generateProof } from '../preimage-snark'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={() => generateProof(
          {
            "preimage": "5",
            "required": "19065150524771031435284970883882288895168425523179566388456001105768498065277",
            "nonce" : "1"
        }, 
        '/main.wasm',
        '/main_0001.zkey'
        )}>Click Me</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
